- websocket_service.go
- websocket_service_test.go
API Documentation: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#individual-symbol-ticker-streams .
Individual Symbol Ticker Streams: 24hr Ticker statistics for a single symbol pushed every second
All Market Tickers Stream: 24hr Ticker statistics for all symbols in an array pushed every second
There is also some undocumented way to set period of updates (as seen on finance itself) but it needs further investigation.
> Add Single Market and All Markets Statistics streams

- account_service_test.go
- client.go
- exchange_info_service.go
- exchange_info_service_test.go
- order_service.go
- order_service_test.go
- ticker_service.go
- ticker_service_test.go
At first I tried doing a dynamic JSON unmarshaling (something like [this](http://gregtrowbridge.com/golang-json-serialization-with-interfaces/)) for the filters, using the `filterType`, but I don't think it's really possible as the struct returned from the client's method can't be really dynamic.
I have another idea, which is to create a `Filter` struct that will look something like this:
type Filter struct {
Price PriceFilter
LotSize LotSizeFilter
MinNotinal MinNotionalFilter
}
type PriceFilter struct {
MinPrice string
MaxPrice string
TickSize string
}
type LotSizeFilter struct {
MinQuantity string
MaxQuantity string
StepSize string
}
type MinNotionalFilter struct {
MinNotional string
}
and to create them manually by iterating over the filters list.
Tell me if you think it is better.
>  Add missing fields to ExchangeInfo and CreateOrderResponse; FOK option; Single symbol bookTicker method

- order_service.go
`price` and `timeInForce` params [should be optional ](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade) for MARKET orders.
Now they are indeed optional.
Before that fix, placing a market order triggered this response:
{
"code": -1105,
"msg": "Parameter 'timeInForce' was was empty."
}
> Fix MARKET orders

- client.go
"Context-Type" should be "Content-Type"
> Fix typo in header key

- websocket_service.go
- websocket_service_test.go
Lesser known endpoint which Binance hasn't documented.  `/!miniTicker@arr` returns mini version of ticker data.  Library users will be able to take advantage of a reduced payload
> Added new miniticker ws endpoint and unit tests

- client.go
- order_service.go
- order_service_test.go
Hi,
New market orders to /api/v3/order can specify a newOrderRespType parameter, which - if set to FULL - returns some details of the trades created to fill the order.
(This means if I do a market order, I can get all the necessary trade details in the one request instead of having to loop and poll for updates to trades. I'm not convinced market orders are the way I want to trade but I did want to try it out.)
So I updated the CreateOrderService and CreateOrderResponse to handle the newOrderRespType.
I got stuck not knowing which way you wanted to approach testing of it though, so I just copied the existing TestCreateOrder test to TestCreateOrderFull and added fill data and checks to it.
> 'Create' market orders can specify a fuller response

- websocket.go
- websocket_service.go
My attempt to implement the ping-pong keepalive mechanism. Since I didn't want to break the compatibility, the timeout is set to constant 60 seconds.
> Add websocket keepalive

- order_service.go
It has to be possible to load the open orders without any symbol.
[docs](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#current-open-orders-user_data)
> Do not require symbol

- websocket.go
Hi,
I looks a bit unnecessary to spawn a new goroutine for every websocket message (price update). If there was a specific reason please let me know. 
Thanks for the lib!
> Dont use goroutine for every ws frame

- withdraw_service.go
- withdraw_service_test.go
CreateWithdrawService.Do got response: 
`{"msg":"Signature for this request is not valid.","success":false}`
According to Binance's [API Doc](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#signed-endpoint-examples-for-post-wapiv3withdrawhtml)
> Note that for wapi, parameters must be sent in query strings.
> Fix CreateWithdrawService: signature for this request is not valid

- client.go
- margin_service.go
- margin_service_test.go
Missed API function
Get all margin pairs (MARKET_DATA)
Get /sapi/v1/margin/allPairs
> get all margin pairs

- websocket_service.go
- websocket_service_test.go
Unfortunately, the base URL for the Future User Data Stream is different than for Spot and Margin as mentioned here: https://binance-docs.github.io/apidocs/futures/en/#user-data-streams. I've added a basic support to it.
> Add base URL for Future User Data Stream

- futures/client.go
- futures/position_margin_history.go
- futures/position_margin_history_test.go
Implementing "Get Postion Margin Change History"
I must say that there is currently a bug in the Binance API itself (which I've reported but feel free to report too). The request will fail if the API key has "read only" permission, even though it's a GET request. The permission "Enable Future" must be enabled too...
> Position margin history

- ticker_service.go
- ticker_service_test.go
reason: a filed lost : lastQTY
add field in `PriceChangeStats` struct` and verify with `TestPriceChangeStats()` function
reference: https://binance-docs.github.io/apidocs/spot/cn/#24hr
> v3 ticker add lastQTY field

- withdraw_service.go
- withdraw_service_test.go
This PR updates the `Withdraw` implementation with all the [missing options](https://binance-docs.github.io/apidocs/spot/en/#withdraw), including `addressTag` and transaction info.
It also changes the signature a bit as Withdraw does return a response, and that was currently not supported. I decided to stick with returning the response container as it actually enables to expose all attributes and potentially further data in the future (like headers).
I found that `ListWithdrawsService` and `ListDepositsService`, for instance, return the inner set of entries rather than a response. I think returning the response would be appropriate as well even in those scenarios, but I'm not going to make changes in this PR outside the scope. `Withdraw` response doesn't have this problem anyways, as it's …
> Withdraw: Add missing options

- client.go
- deposit_service.go
- deposit_service_test.go
- withdraw_service.go
Tests are passing. I also tested it live, and that's how I discovered the undocumented `url` response field.
Closes https://github.com/adshao/go-binance/issues/67
> Add depositAddress API

- futures/order_service.go
- futures/order_service_test.go
Adds the `ClosePosition` field to the `Order` struct in the `futures` package. You can see that field in the response examples of the following API endpoints:
https://binance-docs.github.io/apidocs/futures/en/#query-order-user_data
https://binance-docs.github.io/apidocs/futures/en/#query-current-open-order-user_data
https://binance-docs.github.io/apidocs/futures/en/#current-all-open-orders-user_data
> Add ClosePosition field to Order struct

- futures/client.go
- futures/order_service.go
- futures/order_service_test.go
- v2/futures/client.go
- v2/futures/order_service.go
- v2/futures/order_service_test.go
Adds a `NewOrderResponseType` method to the futures `CreateOrderService` struct in order to set the `newOrderResponseType` query parameter. Docs for endpoint and option here: https://binance-docs.github.io/apidocs/futures/en/#new-order-trade. Changing the `newOrderResponseType` does not actually change the type of the response so it is compatible with the current `CreateOrderResponse` type. 
The PR also removes the `NewOrderRespTypeFULL` variant of the `NewOrderRespType` enum from the futures package. This variant does not exist within the futures API.
> add NewOrderResponseType to futures order service

- futures/order_service.go
- futures/order_service_test.go
- v2/futures/order_service.go
- v2/futures/order_service_test.go
Adds closePosition param to futures order service. Documentation here: https://binance-docs.github.io/apidocs/futures/en/#new-order-trade
> Add closePosition param to futures order service

- client.go
- margin_order_service.go
- margin_service.go
- order_service.go
- trade_service.go
Support for isolated margin order in APIs was added on 2020-07-28 [https://binance-docs.github.io/apidocs/spot/en/#change-log](https://binance-docs.github.io/apidocs/spot/en/#change-log)
> Add support for creating, canceling and listing isolated margin orders

- futures/client.go
- futures/trade_service.go
- futures/trade_service_test.go
- v2/futures/client.go
- v2/futures/trade_service.go
- v2/futures/trade_service_test.go
Adds service `ListAccountTradeService` for the futures account trade list endpoint: https://binance-docs.github.io/apidocs/futures/en/#account-trade-list-user_data
> Add AccountTradeListService

- futures/income_history.go
- futures/income_history_test.go
- v2/futures/income_history.go
- v2/futures/income_history_test.go
Adds fields TranID and TradeID to the futures IncomeHistory type. Relevant JSON schema definition here: https://binance-docs.github.io/apidocs/futures/en/#get-income-history-user_data
> Add TranId and TradeID to IncomeHistory

- futures/income_history.go
- futures/income_history_test.go
- v2/futures/income_history.go
- v2/futures/income_history_test.go
Fixes the type for TranID. The documentation says that it is a string, but the API returns an int. 
https://binance-docs.github.io/apidocs/futures/en/#get-income-history-user_data
> Fix TranID type on IncomeHistory

- v2/client.go
- v2/order_service.go
- v2/order_service_test.go
Adds new CancelOpenOrdersService to cancel all open spot orders for the given symbol. Documentation for endpoint here: https://binance-docs.github.io/apidocs/spot/en/#cancel-all-open-orders-on-a-symbol-trade
The API returns a mixed type array. I could not find any precedent pattern within the library for how to handle that, so I have split the response body into two slices:
```golang
type CancelOpenOrdersResponse struct {
Orders    []*CancelOrderResponse
OCOOrders []*CancelOCOResponse
}
```
> Add CancelOpenOrdersService

- v2/futures/account_service.go
- v2/futures/account_service_test.go
AccountPosition added 4 fields that were missing. These are rather important to have as they are giving useful information about your futures open positions, something that was missing for a long time from Binance it seems.
https://binance-docs.github.io/apidocs/futures/en/#account-information-v2-user_data
> AccountPosition adding missing 4 fields

- websocket_service.go
- websocket_service_test.go
These params are available for the depth streams, but were not available through the API:
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#partial-book-depth-streams
This change simply adds support for 100ms to the single-symbol depth and partial depth streams, but not to the WsCombinedPartialDepthServe
> Support 100ms streams for depth and partial depth

- v2/futures/client.go
- v2/futures/exchange_info_service.go
- v2/futures/exchange_info_service_test.go
Updates futures exchange info with new fields and filters.
Endpoint docs: https://binance-docs.github.io/apidocs/futures/en/#exchange-information
> Add new fields and filter to futures exchange info

- delivery/client.go
- delivery/depth_service.go
- delivery/user_stream_service.go
- delivery/user_stream_service_test.go
- delivery/websocket.go
- delivery/websocket_service.go
- delivery/websocket_service_test.go
- v2/delivery/client.go
- v2/delivery/depth_service.go
- v2/delivery/user_stream_service.go
- v2/delivery/user_stream_service_test.go
- v2/delivery/websocket.go
- v2/delivery/websocket_service.go
- v2/delivery/websocket_service_test.go
- WsAggTradeServe
- WsIndexPriceServe
- WsMarkPriceServe
- WsPairMarkPriceServe
- WsKlineServe
- WsContinuousKlineServe
- WsIndexPriceKlineServe
- WsMarkPriceKlineServe
- WsMiniMarketTickerServe
- WsAllMiniMarketTickerServe
- WsMarketTickerServe
- WsAllMarketTickerServe
- WsBookTickerServe
- WsAllBookTickerServe
- WsLiquidationOrderServe
- WsAllLiquidationOrderServe
- WsPartialDepthServe
- WsDiffDepthServe
Note that all available ws have been implemented (even the ones not yet in the future package)
- Add user stream service
> Delivery API (Coin-M) - All WebSocket Services

- delivery/client.go
- delivery/position_risk.go
- delivery/position_risk_test.go
- v2/delivery/client.go
- v2/delivery/position_risk.go
- v2/delivery/position_risk_test.go
Add position risk service. (https://binance-docs.github.io/apidocs/delivery/en/#position-information-user_data)
Delivery Position risk service differs from Futures Position risk service with the `pair` and `marginAsset` parameters
#150 and #145
> Delivery API (CoinM futures) - Add PositionRisk Service

- delivery/client.go
- delivery/server_service.go
- delivery/server_service_test.go
- v2/delivery/client.go
- v2/delivery/server_service.go
- v2/delivery/server_service_test.go
Add server services
- ping https://binance-docs.github.io/apidocs/delivery/en/#test-connectivity
- time https://binance-docs.github.io/apidocs/delivery/en/#check-server-time
#150 and #145
> Delivery API (CoinM futures) - Add Server Services (ping and time)

- margin_order_service.go
Fixes #196.
#161 added the `IsIsolated()` member function to both `ListMarginOpenOrdersService` and `ListMarginOrdersService`, but in the latter it was not effective (the `isIsolated` field was never populated in the request performed by `Do`).
This change fixes that by adding the `isIsolated` property to `ListMarginOpenOrdersService`'s requests.
cc @anujm08
> Fix isIsolated in ListMarginOpenOrdersService

- v2/websocket_service.go
- v2/websocket_service_test.go
This allows to monitor Aggregated Trades for multiple symbols via a single websocket connection
> Add WsCombinedAggTradeServe

- v2/client.go
- v2/order_service.go
- v2/order_service_test.go
- missing listClientOrderID setter for OCO create
- Cancel OCO service (https://binance-docs.github.io/apidocs/spot/en/#cancel-oco-trade)
> Better support for OCO

- v2/asset_detail_service.go
- v2/asset_detail_service_test.go
If you run this code, which JSON marshalls your assets to STDOUT:
```go
assets, err := client.NewGetAssetDetailService().Do(context.Background())
if err != nil {
log.Fatal(err)
}
bs, err := json.Marshal(assets)
if err != nil {
log.Fatal(err)
}
fmt.Println(string(bs))
```
You get this unmarshalling error:
```
2021/02/27 21:35:08 json: cannot unmarshal number into Go struct field AssetDetail.assetDetail.minWithdrawAmount of type string
exit status 1
```
This PR simply fixes the datatype of the `assetDetail.minWithdrawAmount` field to the correct `float64`. With the fixed datatype, the marshalling now works:
```
{"1INCH":{"minWithdrawAmount":6.14,"depositStatus":true,"withdrawFee":3.07,"withdrawStatus":true,"depositTip":""},"AAVE":{"minWithdrawAmount":0.2,"depositStatus":true,"withdrawFee":0. …
```
> Make AssetDetail.MinWithdrawAmount a float64.

- v2/futures/websocket_service.go
EstimatedSettlePrice is missing which caused wrong markprice
after parsed JSON.
> Fix mark price issue of futures websocket

- v2/websocket_service.go
- v2/websocket_service_test.go
This allows to monitor ticker statistics for multiple symbols via a single websocket connection
> add WsCombinedMarketStatServe

- v2/futures/mark_price.go
Fix unmarshal issue when there's only one object in returned result.
error message:
json: cannot unmarshal object into Go value of type []*futures.PremiumIndex
> fix PremiumIndex unmarshal issue when returns only one object

- v2/futures/order_service.go
- v2/futures/order_service_test.go
https://binance-docs.github.io/apidocs/futures/en/#new-order-trade
> Include the PriceProtect field into the order service of futures

- v2/futures/account_service.go
- v2/futures/account_service_test.go
- v2/futures/mark_price.go
- v2/futures/mark_price_test.go
Add missing fields for following APIs.
fapi/v1/account
/fapi/v1/leverageBracket
> add missing fields for futures leverageBracket and account

- v2/futures/depth_service.go
Now they get replaced by a unified type called PriceLevel.  Bid and
Ask remain available as type aliases, which is backward compatible,
but also allows code to treat both bids and asks the same.
> Unify futures.Bid and futures.Ask

- v2/common/priceLevel.go
- v2/delivery/depth_service.go
- v2/depth_service.go
- v2/futures/depth_service.go
- v2/websocket_service.go
- v2/websocket_service_test.go
Hi!
I've needed to work with asks\bids from spot and futures market simultaneously, that's why I think that asks and bids should be the same type (I moved them into common package).
In addition, I changed the name of update ID, because previous name wasn't clear enough (binance docs are using "lastUpdateId").
> Changed type of asks and bids to one type. 

- v2/margin_service.go
The isolatedSymbol parameter is required to borrow and repay loan for isolated margin account.
See https://binance-docs.github.io/apidocs/spot/en/#margin-account-repay-margin and https://binance-docs.github.io/apidocs/spot/en/#margin-account-borrow-margin
> Add isIsolated parameter to MarginLoanService and MarginRepayService

- v2/delivery/client.go
- v2/delivery/ticker_service.go
- v2/delivery/ticker_service_test.go
Add support for endpoints:
- `/dapi/v1/ticker/24hr`
- `/dapi/v1/ticker/price`
- `/dapi/v1/ticker/bookTicker`
Binance Delivery API forbits `pair` and `symbol` parameter to be sent together. So I am not sure if this should be handled at the SDK level or just let the API return an error.
> Delivery API (CoinM futures) - Add Ticker Service

- v2/futures/exchange_info_service.go
Fixes `json: cannot unmarshal number 1624608000000 into Go struct field Symbol.symbols.settlePlan of type int`
> Symbol.symbols.settlePlan should be int64

- v2/order_service.go
Response to /api/v3/order request has field [OrderListId](https://binance-docs.github.io/apidocs/spot/en/#query-order-user_data), but it is not parsed currently.
> Add OrderListId field to Order struct

- v2/trade_service.go
According to the binance document, the `api/v3/myTrades` has a new optional field `orderId`.
so, I added it to the code.
> myTrades set filed orderId

- v2/asset_dividend_service.go
- v2/asset_dividend_service_test.go
- v2/client.go
Added the ability to receive a list of dividends
Taken from branch v1
> Add Dividend Service

- v2/client.go
- v2/savings_service.go
- v2/savings_service_test.go
Add 2 new services related to the "Savings"
- `ListSavingsFixedAndActivityProductsService` 
- https://binance-docs.github.io/apidocs/spot/en/#get-fixed-and-activity-project-list-user_data
- `ListSavingsFlexibleProductsService` 
- https://binance-docs.github.io/apidocs/spot/en/#get-flexible-product-list-user_data
> [Savings] Add services to list Flexible and Fixed products

- v2/client.go
- v2/margin_service.go
Implement of Get All Margin Assets (MARKET_DATA)
GET /sapi/v1/margin/allAssets
Response: 
```
[
{
"assetFullName": "USD coin",
"assetName": "USDC",
"isBorrowable": true,
"isMortgageable": true,
"userMinBorrow": "0.00000000",
"userMinRepay": "0.00000000"
},
{
"assetFullName": "BNB-coin",
"assetName": "BNB",
"isBorrowable": true,
"isMortgageable": true,
"userMinBorrow": "1.00000000",
"userMinRepay": "0.00000000"
},
{
"assetFullName": "Tether",
"assetName": "USDT",
"isBorrowable": true,
"isMortgageable": true,
"userMinBorrow": "1.00000000",
"userMinRepay": "0.00000000"
},
{
"assetFullName": "etherum",
"assetName": "ETH",
"isBorrowable": true,
"isMortgageable": true,
"userMinBorrow": "0.00000000",
"userMinRepay": "0.00000000"
},
{
"assetFullName": "Bitcoin",
"assetName": "BTC", …
```
> Impl /sapi/v1/margin/allAssets

- v2/margin_service.go
The `isolatedSymbol` parameter is required to get the max borrow amount of an isolated margin account.  
See https://binance-docs.github.io/apidocs/spot/en/#query-max-borrow-user_data
> Add isolatedSymbol parameter to GetMaxBorrowableService

- .gitignore
- v2/client.go
- v2/fiat_service.go
- v2/fiat_service_test.go
Add the [fiat endpoints](https://binance-docs.github.io/apidocs/spot/en/#fiat-endpoints):
- [Fiat Deposit/Withdraw History](https://binance-docs.github.io/apidocs/spot/en/#get-fiat-deposit-withdraw-history-user_data) : `/sapi/v1/fiat/orders`
- [Fiat Payments History](https://binance-docs.github.io/apidocs/spot/en/#get-fiat-payments-history-user_data) : `/sapi/v1/fiat/payments`
> Add fiat endpoints

- v2/websocket_service.go
- v2/websocket_service_test.go
- Adds `WsCombinedDepthServe100Ms` in the same fashion as `WsDepthServe100Ms`
> Add function for Diff. Depth Stream with an update speed of 100ms

- v2/delivery/account_service.go
- v2/delivery/account_service_test.go
add positionAmt in both account_service.go and account_servie_test.go
> fix delivery API without positionAmt bugs

- v2/client.go
- v2/interest_history_service.go
- v2/interest_history_service_test.go
Add the [Interest History](https://binance-docs.github.io/apidocs/spot/en/#get-interest-history-user_data-2) service : /sapi/v1/lending/union/interestHistory
> Add the Interest History service

- v2/client.go
- v2/margin_service.go
- v2/margin_service_test.go
Add endpoint : https://binance-docs.github.io/apidocs/spot/en/#get-all-isolated-margin-symbol-user_data
> Add getIsolatedMarginAllPairs endpoint

- v2/order_service.go
As per [binance docs](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade) (and tested empirically) fills have a field `tradeId` which is very useful to perform cross-matching in between the websocket feed and the standar API calls.
> feat: add trade ID field to order fills

- v2/client.go
- v2/trade_fee_service.go
- v2/trade_fee_service_test.go
Add:
- `trade_fee_service` with tradeFee structure representation
- basic tests for that service
- client `NewTradeFeeService` to allow creation of new Trade Fee service
Fix #253
> Add tradeFee method support

- v2/delivery/websocket_service.go
- v2/delivery/websocket_service_test.go
Add methods to get partial and diff depth with rate for delivery websocket API
Copied some logic from futures
> feat: Partial and diff depth with rate for delivery websocket

- v2/deposit_service.go
- v2/deposit_service_test.go
It is written in the [documentation](https://binance-docs.github.io/apidocs/spot/en/#deposit-history-supporting-network-user_data) that the field is string, but in fact it returns int, which causes an error.
However, elsewhere in the [documentation](https://binance-docs.github.io/apidocs/spot/en/#all-coins-39-information-user_data) the field is already an integer.
`"unLockConfirm": 0,  // confirmation number for balance unlock`
> Fix Unmarshal error on ListDeposits API response

- v2/ticker_service.go
- v2/ticker_service_test.go
#380 
Added the "Symbols" parameters as specified in [https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#symbol-price-ticker](url)
Corresponding unit test "TestListPricesForMultipleSymbols" was added, too.
> Added a "Symbols" parameters to ListPricesService

- v2/futures/client.go
- v2/futures/openinterest_service.go
- v2/futures/openinterest_service_test.go
Include service for:
- Open Interest data: https://binance-docs.github.io/apidocs/futures/en/#open-interest
- Open interest statistics: https://binance-docs.github.io/apidocs/futures/en/#open-interest-statistics
Example of usage:
```go
openInterest, err := c.client.NewGetOpenInterestService().Symbol("BTCUSDT").Do(ctx)
if err != nil {
return err
}
fmt.Printf(" %+v\n", openInterest)
statistics, err := c.client.NewOpenInterestStatisticsService().
Symbol("BTCUSDT").Period("1h").
Limit(24).
Do(ctx)
for i, statistic := range statistics {
fmt.Printf("%d: %+v\n", i, statistic)
}
```
> feat(futures): include get open interest call

- .gitattributes
- v2/client.go
- v2/ticker_service.go
- v2/ticker_service_test.go
Addresses issue #403 
- Added `.gitattributes` to prevent the git of other platforms from modifying files line ending (Windows Git is known for doing that). I set it to `LF` since it's wide compatible.
- Added new service: **ListSymbolTickerService**
- Added test case for the new service
> #403 - Added support for GET /api/v3/ticker

- v2/futures/client.go
- v2/futures/longshort_ratio_service.go
- v2/futures/longshort_ratio_service_test.go
- v2/futures/openinterest_service_test.go
Implements Long Short Ratio Statistics: https://binance-docs.github.io/apidocs/futures/en/#long-short-ratio
> feat(futures): include long short ration service

- v2/client.go
- v2/rate_limit_service.go
- v2/rate_limit_service_test.go
Add RateLimitService to query trade limitations. Ref: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#query-current-order-count-usage-trade 
For compatibility, I didn't alter field types in ExchangeInfoService.
https://github.com/adshao/go-binance/blob/f3bd66ee84caca1dd0e69e517d34319e145790a6/v2/delivery/exchange_info_service.go#L43-L49
> feat: Implement RateLimitService

- v2/client.go
- v2/subaccount_service.go
- v2/subaccount_service_test.go
> feat implement SubAccountListService

- v2/futures/commission_rate_service.go
- v2/futures/commission_rate_service_test.go
Found that this api needs a signature and the response is not an array
ref: https://binance-docs.github.io/apidocs/futures/en/#user-commission-rate-user_data
> Fix fapi commission_rate_service (/fapi/v1/commissionRate) no signature param error

- v2/websocket_service.go
error as below:
`json: cannot unmarshal object into Go value of type []spotws.WsOCOOrder`
I fixed it and then realised that we are not tracking userData `AccountUpdate` (not sure if you were blocked by this unmarshal issue), so I added it as well.
Otherwise we may have the same error :
`json: cannot unmarshal object into Go value of type []spotws.WsAccountUpdate`
> Fix userDataStream json `array` unmarshal err

- v2/ticker_service.go
- v2/ticker_service_test.go
add param `symbols` for ListPriceChangeStatsService
Ref: https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics
> Add param `symbols` for ListPriceChangeStatsService

- v2/futures/client.go
- v2/futures/continuous_kline_service.go
- v2/futures/continuous_kline_service_test.go
- v2/futures/websocket_service.go
- v2/futures/websocket_service_test.go
Hello, I used this module and found that the relevant interfaces of the future part of the continuous contract kline were not implemented. So I implemented a copy and hope that the author can incorporate it.
rest api:
websocket:
> The futures module adds the continuous contract Kline rest interface and websocket interface

- v2/futures/trade_service.go
Adds support for the `orderId` param on the `/fapi/v1/userTrades` endpoint
---
📝 https://binance-docs.github.io/apidocs/futures/en/#account-trade-list-user_data
> feat(/fapi/v1/userTrades): Add support for `orderId` param

- v2/client.go
- v2/subaccount_service.go
- v2/subaccount_service_test.go
Get Detail on Sub-account's Futures Account (For Master Account)
ref: https://binance-docs.github.io/apidocs/spot/en/#get-detail-on-sub-account-39-s-futures-account-for-master-account
> Add SubAccountFuturesAccountService

- v2/client.go
- v2/exchange_info_service.go
- v2/exchange_info_service_test.go
- v2/futures/client.go
I found some symbols filter have changned in binance, eg. for maticusdt, the following format is returned:
```json
{
"filterType": "NOTIONAL",
"minNotional": "5.00000000",
"applyMinToMarket": true,
"maxNotional": "9000000.00000000",
"applyMaxToMarket": false,
"avgPriceMins": 5
},
```
> Add NOTIONAL filter support

- v2/futures/client.go
- v2/futures/position_service.go
- v2/futures/position_service_test.go
I found the endpoint `/fapi/v1/multiAssetsMargin` is not supported yet to get or change the multi-asset mode of a user.
I added the related services accordingly in the following files in `v2/futures`.
- client.go
- position_service.go
- position_service_test.go
> Add MultiAssetModeService for Future

- v2/account_service.go
- v2/account_service_test.go
Adding `commissionRates` into the account service response. Fixing open issue **#492**
> Adding `commissionRates` into the account service response

- v2/futures/account_service.go
- v2/futures/account_service_test.go
futures v1 account api was no longer surpported in 2023-07-15 accorindg to [2023-06-28 notice](https://binance-docs.github.io/apidocs/futures/en/#change-log).
upgrade `/fapi/v1/account` to [/fapi/v2/account](https://binance-docs.github.io/apidocs/futures/en/#account-information-v2-user_data)
> upgrade futures account service to v2 version

- v2/futures/order_service.go
As [/fapi/v1/order api](https://binance-docs.github.io/apidocs/futures/en/#new-order-trade) says, parameter `quantity` is optional, it cannot be sent with closePosition=true(Close-All). 
So we should check its value before set it.
> set futures create order parameter quantity as optional

- v2/order_service.go
Got an error, when create order on 32bit system.
Err: binance.CreateOrderResponse.Fills: []*binance.Fill: binance.Fill.TradeID: ReadInt32: overflow: 3183180150, error found in #10 byte of ...|3183180150}],"selfTr|..., bigger context ...|3587","commissionAsset":"BNB","tradeId":3183180150}],"selfTradePreventionMode":"NONE"}|...
Need to change the type of field TradeID from int to int64, because this field no longer places identifiers in systems where int is interpreted as int32. As a result, the order is created on Binance, but due to the fact that unmarshaling is broken, we cannot receive a correct response.
> Update TradeID type to int64

- v2/futures/position_risk.go
- v2/futures/position_risk_test.go
`breakEvenPrice` is available in binance's production server and API doc but not applied in the source code yet.
I just added those.
> Added breakEvenPrice data

- v2/futures/client.go
- v2/futures/index_price_kline_service_test.go
- v2/futures/premium_index_kline_service.go
- v2/futures/premium_index_kline_service_test.go
The library currently doesn't support fetching premium index klines. I added a new service that implements this functionality.
Also, I discovered `v2/futures/index_price_kline_service_test.go` doesn't call method for fetching index price klines (despite its name). I replaced `NewKlinesService()` with `NewIndexPriceKlinesService()` and made a couple of other changes to make tests pass.
Sorry for making two almost unrelated changes in one PR. I believe it won't be a big problem apart from being a bad practice.
> feat(futures): add premium index klines service

- v2/client.go
- v2/options/client.go
- v2/options/client_test.go
- v2/options/depth_service.go
- v2/options/depth_service_test.go
- v2/options/exchange_info_service.go
- v2/options/exchange_info_service_test.go
- v2/options/kline_service.go
- v2/options/kline_service_test.go
- v2/options/order_service.go
- v2/options/order_service_test.go
- v2/options/request.go
We init European Options client ant implemented its main services including:
* [order book](https://binance-docs.github.io/apidocs/voptions/en/#order-book)
* [exchange information](https://binance-docs.github.io/apidocs/voptions/en/#exchange-information)
* [kline data](https://binance-docs.github.io/apidocs/voptions/en/#kline-candlestick-data)
* [new order](https://binance-docs.github.io/apidocs/voptions/en/#new-order-trade)
* [list orders](https://binance-docs.github.io/apidocs/voptions/en/#query-current-open-option-orders-user_data)
* [get order](https://binance-docs.github.io/apidocs/voptions/en/#query-single-order-trade)
* [cancel order](https://binance-docs.github.io/apidocs/voptions/en/#cancel-option-order-trade)
* [cancel all …
> init options client and implement kline/order/exchange/depth services

- v2/futures/ticker_service.go
GET /fapi/v2/ticker/price: this is v2 endpoint for querying latest price. It has same parameters and response as the GET /fapi/v1/ticker/price, and it offers lower latency and consume less of the IP rate limit. Please note that the GET /fapi/v1/ticker/price will be deprecated in the future, with the exact timing to be determined.
https://binance-docs.github.io/apidocs/futures/en/#change-log
> change /fapi/v1/ticker/price to v2 version /fapi/v2/ticker/price

- v2/websocket_service.go
- v2/websocket_service_test.go
Update the WsUserDataEvent struct according to the latest version of Binance documentation and solve the current case sensitivity problem. 
This update has to make a few changes that break compatibility. Currently, only the e and E fields are common to all events. There is a problem that fields with the same name have different meanings and types in different events. 
For example, the field "u" is the last update timestamp of the account in the outboundAccountPosition event, but it is the Trade Group Id in the executionReport event. 
Field "a" represents the asset in the outboundAccountPosition and balanceUpdate events and is of type string, but represents the Allocation ID in the executionReport event and is of type int.
In view of this, I have moved the fields "T" and "u" out of the …
> update WsUserDataEvent struct

- v2/futures/client.go
- v2/futures/funding_rate_history.go
- v2/futures/funding_rate_history_test.go
- v2/futures/funding_rate_info.go
- v2/futures/funding_rate_info_test.go
The market client has been modified to enable the retrieval of funding rate data with the following changes:
- NewFundingRateHistoryService now fetches funding rate history data using the Rest API.
- NewFundingRateInfoService now retrieves symbols' funding rate information using the Rest API.
Tests for the new functions have been created following the same approach as other tests in the package.
> Add functions to fetch funding rate data from market

- v2/delivery/order_service.go
- v2/delivery/order_service_test.go
- v2/futures/order_service.go
- v2/futures/order_service_test.go
There are should be STRING types in this fields. 
BOOL type is still working in single order requests, but not is batch ones.
> changed bool types to string in reduceOnly, closePosition, priceProtect.

- v2/client.go
- v2/subaccount_service.go
- v2/subaccount_service_test.go
- v2/user_universal_transfer.go
- v2/user_universal_transfer_test.go
1. Implement [Sub-account Transfer History (For Sub-account)](https://binance-docs.github.io/apidocs/spot/en/#sub-account-transfer-history-for-sub-account)
1. Implement [Query User Universal Transfer History](https://binance-docs.github.io/apidocs/spot/en/#query-user-universal-transfer-history-user_data)
2. Refactor CreateUserUniversalTransferService, add `UserUniversalTransferType` and `UserUniversalTransferStatusType`
> Implement subaccount transfer history and refactor user universal transfer

- v2/client.go
- v2/common/errors.go
- v2/delivery/client.go
- v2/futures/client.go
- v2/options/client.go
In some cases, the REST API will return a response with the body:
```json
{"error": "Internal error: 1"}
```
When this happens, it returns an ApiError that shows nothing meaningful when the user calls the REST API interface. Optimize the request error handling process to make the error more meaningful.
> Optimize request error handling process

- v2/client.go
- v2/common/sign.go
- v2/delivery/client.go
- v2/futures/client.go
- v2/options/client.go
1. Binance supports three message signing methods. The current message signing method in the module only supports HMAC. The updated feature will add support for RSA and Ed25519 key types, expanding the range of cryptographic algorithms available for message signing.
> feature: support signature key Rsa and ed25519

- v2/delivery/websocket_service.go
- v2/futures/websocket_service.go
- v2/options/order_service.go
- v2/options/order_service_test.go
1. When calling `batch ordering and batch cancellation` in the options package, the response may contain `{"code": -1121, "msg": "Invalid symbol."}` objects. Adjust the return value type of the current interface to handle this case.
2. When the `listenKey` expires, the `Time` field in the JSON string for `futures.WsUserDataEvent` may be of type `string`, which can cause JSON deserialization errors. Fix this issue. #524
> fix batchOrder response and fix futures.WsUserDataEvent.Time error while calling json.Unmarshal

- v2/client.go
- v2/futures_service.go
- v2/futures_service_test.go
[Get Future TickLevel Orderbook Historical Data Download Link (USER_DATA)](https://binance-docs.github.io/apidocs/spot/en/#get-future-account-transaction-history-list-user_data)
@adshao please review it
> implement futures orderbook history

- v2/asset_detail_service.go
- v2/asset_detail_service_test.go
This Pull Request adds missing fields (EstimatedArrivalTime, Busy, ContractAddressUrl, ContractAddress) in GetAllCoinsInfoService Network structure
> fix: added missing fields in GetAllCoinsInfoService Network structure

- v2/futures/client.go
- v2/futures/order_service.go
- v2/futures/order_service_test.go
I just used copy past strategy to make modify order service for futures-api which uses 'put' method in request to perform this operation
> Make future order ModifyService

- v2/futures/client.go
- v2/futures/order_service.go
- v2/futures/order_service_test.go
Introduce the right way to implement Modify Order endpoint.
I don't know how the previous version of this endpoint was approved - really no idea. I think pull requests should be checked more thoroughly.
> Fix Modify Order Endpoint : PUT /fapi/v1/order

- v2/client.go
- v2/futures_algo_service.go
- v2/futures_algo_service_test.go
implement futures algo [endpoint](https://binance-docs.github.io/apidocs/spot/en/#futures-algo-endpoints), including 6 apis:
1. create futures vp order
2. create futures twap order
3. list open algo orders
4. list historical algo orders
5. cancel algo order
6. get algo sub orders
@adshao  plz review it
> finish futures algo services

- v2/futures/websocket_service.go
code is similar with spot part
> support combined futures bookticker ws event

- v2/futures/client.go
- v2/futures/convert_service.go
- v2/futures/convert_service_test.go
docs here https://developers.binance.com/docs/derivatives/usds-margined-futures/convert
> add usds-futures convert service

- v2/exchange_info_service.go
- v2/exchange_info_service_test.go
This PR adds support for the `permissionSets` field in the Binance Exchange Info API response. The field was recently added to the API and contains information about trading permissions for each symbol.
Closes https://github.com/adshao/go-binance/issues/640
> feat: Add permissionSets field to exchange info response

- v2/futures/client.go
- v2/futures/position_risk.go
- v2/futures/position_risk_test.go
1. support /fapi/v3/positionRisk, close #602
> support /fapi/v3/positionRisk

- v2/futures/client.go
- v2/futures/order_service.go
- v2/futures/order_service_test.go
Implementation of order batches modification and test for it. Presented in the official api of binance: https://developers.binance.com/docs/derivatives/usds-margined-futures/trade/rest-api/Modify-Multiple-Orders
> Add modify batch orders feature #647

- v2/futures/client.go
- v2/futures/position_risk.go
- v2/futures/position_risk_test.go
- v2/futures/rebate_newuser.go
In my opinion, we shouldn't make breaking changes and replace v2 endpoints with v3 ones in terms of backward compatibility. 
This repository has 1.6k stars and almost 700 forks, and suddenly changing "Position Risk Service" from v2 behavior to v3 shouldn't be allowed, as you make breaking changes out of the blue in lots of other repositories. 
Especially, given that package is v2 library, if you add v3 endpoints in replacement of v2 ones (which are not deprecated), it makes usage of the package kind of confusing as well.
Another point is that there are several v2 endpoints that have v3 versions (e.g. Position Risk, Account, Balance), which were not updated yet. In the future, I would suggest to introduce them like "AccountServiceV3", not "AccountService".
> Futures Position Risk backward compatibility

- v2/order_service.go
- v2/order_service_test.go
The `origQuoteOrderQty` response field was only available on the `Order` struct.
This pull request adds the `OrigQuoteOrderQuantity` field to `CreateOrderResponse` and `CancelOrderResponse`.
Docs: https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#trading-endpoints
> feat: add OrigQuoteOrderQuantity field for order responses

- v2/delivery/websocket.go
- v2/delivery/websocket_service.go
- v2/futures/websocket.go
- v2/futures/websocket_service.go
- v2/options/websocket.go
- v2/options/websocket_service.go
- v2/websocket.go
- v2/websocket_service.go
I implemented this fix according to Binance Websocket General information to avoid  `websocket: close 1006 (abnormal closure): unexpected EOF` errors:
```text
The websocket server will send a ping frame every 20 seconds.
If the websocket server does not receive a pong frame back from the connection within a minute the connection will be disconnected.
When you receive a ping, you must send a pong with a copy of ping's payload as soon as possible.
Unsolicited pong frames are allowed, but will not prevent disconnection. It is recommended that the payload for these pong frames are empty.
```
https://github.com/bnb-chain/websocket/blob/78bda6652e7166759b9f2ed92b4d4c67352bfbab/conn.go#L794
> Fix `websocket: close 1006 (abnormal closure): unexpected EOF` errors when calling `binance.WsCombinedBookTickerServe()`

- v2/delivery/websocket_service.go
- v2/futures/websocket_service.go
- v2/options/websocket_service.go
- v2/websocket_service.go
Binance does not gurantee to send PING messages every 20s, currently it sends PING every 3m, we should not close ws conn with timeout less than the interval between binance sends PINGs. May increase this timeout or remove it in the future.
> Do not close ws conn from client side.

- v2/client.go
- v2/dual_investment_service.go
- v2/dual_investment_service_test.go
- v2/futures/account_service_test.go
Added dual investment service including product listing, position listing, account information, subscription, and auto-compound status modification features. Also included corresponding test cases to ensure functionality correctness and stability.
https://developers.binance.com/docs/dual_investment/quick-start
> feat(dual_investment): Add dual investment service and related tests

- v2/futures/account_service.go
even though in https://developers.binance.com/docs/derivatives/usds-margined-futures/account/rest-api/Account-Information-V2 doesn't specify that `isolatedWallet` is returned with position information, in actual response it returns it like this
```
{
"symbol": "BTCUSDT",
"initialMargin": "0",
"maintMargin": "0",
"unrealizedProfit": "0.00000000",
"positionInitialMargin": "0",
"openOrderInitialMargin": "0",
"leverage": "5",
"isolated": true,
"entryPrice": "0.0",
"breakEvenPrice": "0.0",
"maxNotional": "480000000",
"positionSide": "BOTH",
"positionAmt": "0.000",
"notional": "0",
"isolatedWallet": "0", // we didn't parse this
"updateTime": 1751517998423,
"bidNotional": "0",
"askNotional": "0"
},
```
which I have tested with my account in isolated mode, and it returns the same number as in …
> feat: accountInfoV2 parse isolatedWallet

- .gitignore
- v2/subaccount_service.go
There's a `subUserId` and `remark` field.
Refer: https://developers.binance.com/docs/sub_account/account-management/Query-Sub-account-List
I verified also by manually printing out `data` in fie `client.go` - `callAPI`.
> Add `subUserId` and `remark`

- v2/dual_investment_service.go
- v2/dual_investment_service_test.go
To resolve https://github.com/ccxt/go-binance/issues/756
Adds four undocumented fields returned by the Binance API for settled dual investment positions:
- SettlePrice: Actual market price at settlement
- SettleAmount: Amount received after settlement
- SettleAsset: Coin received (investCoin or exercisedCoin)
- IsExercised: Whether the option was exercised
These fields are only present in API responses for positions with SETTLED status and are essential for
tracking settlement outcomes and calculating profits.
> Added settlement fields to ListDualInvestmentPosition struct
