ccxt/go-binance

.travis.yml
=> Gofmt exclude vendor/

README.md
=> Fix binance api doc url

README.md, websocket.go, websocket_service.go, websocket_service_test.go
=> Add stopC to exit ws serve

trade_service.go, trade_service_test.go
add tests to historical trades.
=> Use TradeV3 for v3 API

websocket_service.go
Does this look good? [#26](https://github.com/adshao/go-binance/issues/26)
Sorry for not including tests but I just started with go yesterday.
=> Trade Streams

websocket_service_test.go
=> Add unit tests

websocket_service.go, websocket_service_test.go
Tests pass and streaming works when used.
=> Added partial depth book streaming to websocket_service

client.go
Hi, I added the missing order types.
=> Add missing conditional order type enums

order_service.go, order_service_test.go
As shown here 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#test-new-order-trade (scroll up a little bit from there)
=> Add cummulativeQuoteQty

client.go, helpers.go, order_service.go, order_service_test.go, ticker_service.go, ticker_service_test.go, trade_service.go, trade_service_test.go
=> Update with v3 APIs

client.go, exchange_info_service.go, exchange_info_service_test.go
=> Add symbol filters

client.go, margin_service.go, margin_service_test.go
=> Add margin APIs for user data stream

exchange_info_service.go, exchange_info_service_test.go
Add OcoAllowed, IsSpotTradingAllowed, IsMarginTradingAllowed in Symbol.
=> update to /api/v3/exchangeInfo

.travis.yml, client.go, margin_order_service.go, margin_order_service_test.go, order_service_test.go
=> Add sideEffectType to margin order

futures_service.go, futures_service_test.go
Despite what the documentation was suggesting.
=> Type is an int64

futures/client.go, futures/position_risk.go, futures/position_risk_test.go
=> Add Position Risk (Future API)

futures/client.go, futures/mark_price.go, futures/mark_price_test.go
A little special here as the response is depending on whether we send a symbol or not. All in all, we return at the end an array.
=> Get leverage brackets

websocket.go, websocket_service.go, websocket_service_test.go
The Testnet Future stream is also having its own endpoint like shown here:
=> Testnet future stream

README.md, client.go, futures/client.go, futures/server_service.go, futures/server_service_test.go, server_service.go, server_service_test.go
Implements https://github.com/adshao/go-binance/issues/127
=> Add optional time offset #127

futures/client.go, futures/order_service.go, futures/order_service_test.go
Add trailing stop market. It's not yet available in the UI but it actually already works in the API.
=> Add trailing stop market

order_service.go, order_service_test.go
=> Add quote order qty

margin_service.go, margin_service_test.go
=> Fix margin requests with secTypeSigned

kline_service.go
=> Remove deprecated v1 APIs as binance updates

futures/client.go, futures/order_service.go, futures/order_service_test.go, futures/position_margin_history.go, futures/position_margin_history_test.go, futures/position_risk.go, futures/position_risk_test.go, futures/position_service_test.go
Add missing fields implemented partially in https://github.com/adshao/go-binance/pull/135
=> Test and add fields for dual side mode

v2/websocket.go, websocket.go
in wsServe (websocket.go) stopC is being checked only after ReadMessage() returns. This bug is not easily noticeable for high frequency streams like the aggregated trades, but for a stream that drops a message rarely (like the user data), it's a problem. The fix I'm proposing waits for the stopC to be closed in a separate goroutine. If doneC is signalled before that, stopC may be ignored.
=> wsServe blocks on ReadMessage and doesn't respect stopC

v2/futures/account_service.go, v2/futures/account_service_test.go
Upgrades the v2 mod to use the v2 futures balance endpoint, as discussed in #160.
=> V2 futures balance

futures/exchange_info_service.go, futures/exchange_info_service_test.go, v2/futures/exchange_info_service.go, v2/futures/exchange_info_service_test.go
Adds BaseAsset and QuoteAsset to the futures exchange info response.
=> Add BaseAsset and QuoteAsset to futures exch info

futures/websocket.go, futures/websocket_service.go, futures/websocket_service_test.go, v2/futures/websocket.go, v2/futures/websocket_service.go, v2/futures/websocket_service_test.go
Adds support for futures websocket market streams.
Closes #149
=> Add futures websocket support

futures/websocket_service.go, futures/websocket_service_test.go, v2/futures/websocket_service.go, v2/futures/websocket_service_test.go
=> Add Event field to futures WsBookTickerEvent

v2/websocket_service.go, v2/websocket_service_test.go
=> Support 100Ms depth sockets for v2 single-ticker depth streams

delivery/client.go, delivery/kline_service.go, delivery/kline_service_test.go, v2/delivery/client.go, v2/delivery/kline_service.go, v2/delivery/kline_service_test.go
- Add Kline Service
Related to #150 and #145
=> Delivery API (CoinM futures) - Add KLine Service

README.md, v2/delivery/client.go, v2/delivery/websocket_service.go
- Add the ability to use the testnet
- This is a very simple implementation. Please, feel free to make comments if you find a more simple/elegant way to do that. (My main issue is to "link" the WS and Client endpoint around a boolean)
- If this way is good for you, I can implement the same for the `futures` package
#191 #150 #145
=> Delivery API : Add testnet

README.md, v2/futures/client.go, v2/futures/websocket_service.go
Add testnet for futures API
#191 #150 #145
=> Futures API : Add testnet

v2/websocket_service.go, v2/websocket_service_test.go
This MR closes https://github.com/adshao/go-binance/issues/155
=> add websocket support for spot book-ticker

v2/delivery/account_service.go, v2/delivery/account_service_test.go, v2/delivery/client.go
Implemented:
- GET /dapi/v1/account 
- GET /dapi/v1/balance
=> Add Delivery account and balance endpoints

v2/futures/position_risk.go
isolatedWallet = isolatedMargin - unRealizedProfit
Having this we can know wallet balance in isolated mode.
No need to calculate it again.
=> Add isolatedWallet and notional in PositionRisk

v2/futures/client.go, v2/futures/order_service.go
support get user's force orders info
=> add /fapi/v1/forceOrders to get user's force orders

v2/futures/mark_price.go, v2/futures/mark_price_test.go
support get PremiumIndex for all symbols rather than only one symbol
=> support get PremiumIndex for all symbols

v2/websocket_service.go, v2/websocket_service_test.go
Hey I add the combined ws api for kline data, could you pls help to review this PR
=> Support combine kline for websocket

v2/futures/position_risk.go, v2/futures/position_risk_test.go
`GET /fapi/v2/positionRisk (HMAC SHA256)`
https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data
=> add interface for /fapi/v2/positionRisk to get positionRisk (#224)

v2/exchange_info_service.go, v2/exchange_info_service_test.go
add intervalNum of rate limit for spot exchange info
=> add intervalNum of rate limit for spot exchange info

v2/margin_order_service.go, v2/margin_order_service_test.go
=> Add support for quoteOrderQty in margin orders

v2/futures/client.go, v2/futures/order_service.go
Added CancelMultiplesOrdersService to cancel multiple orders.
=> Added the possibility to cancel multiple orders in futures

v2/futures/client.go, v2/futures/rebate_newuser.go
Added the endopint to check the brokerage program eligibility of a customer according to the specification included in this doc https://binance-docs.github.io/apiAgent-API-EN/General_EN/ 
This API is useful for brokerage program partner.
=> Binance Api Agent

v2/account_service.go, v2/account_service_test.go
Update account API response base on docs https://binance-docs.github.io/apidocs/spot/en/#account-information-user_data
=> update account struct

README.md, v2/asset_detail_service.go, v2/asset_detail_service_test.go, v2/deposit_service.go, v2/deposit_service_test.go, v2/dust_log_service.go, v2/dust_log_service_test.go, v2/withdraw_service.go, v2/withdraw_service_test.go
=> Change wapi to sapi

v2/futures/client.go, v2/futures/order_service.go
usage:
```go
orders := []*futures.CreateOrderService{}
for i := 0; i < 2; i++ {
o := client.NewCreateOrderService().Symbol(symbol).Price(convertPrice(12.0)).Quantity(convertQty(1.0)).Side(futures.SideTypeBuy).Type(futures.OrderTypeLimit).TimeInForce(futures.TimeInForceTypeGTC)
orders = append(orders, o)
}
resp, err := client.NewCreateBatchOrdersService().OrderList(orders).Do(context.Background())
```
=> batch orders

v2/futures/websocket_service.go
added field according to API Binance documentation
=> added Balance change into WsBalance of Future 

v2/client.go, v2/margin_order_service.go, v2/margin_order_service_test.go, v2/order_service.go
=> Create Margin OCO

v2/client.go, v2/pay_service.go, v2/pay_service_test.go
Add service for pay endpoints: https://binance-docs.github.io/apidocs/spot/en/#pay-endpoints
=> Add pay service

v2/client.go, v2/futures/client.go
For some country ban binance.com site, so we can launch request behind a proxy.
=> adding proxy mode for client.

v2/c2c_service.go, v2/c2c_service_test.go, v2/client.go
Add support for binance c2c service: https://binance-docs.github.io/apidocs/spot/en/#get-c2c-trade-history-user_data
=> Add support for binance c2c service

v2/margin_service.go
update endpoint
https://binance-docs.github.io/apidocs/spot/en/#margin-account-borrow-margin
https://binance-docs.github.io/apidocs/spot/en/#margin-account-repay-margin
=> update MarginLoanService / MarginRepayService

v2/order_service.go, v2/order_service_test.go
Solves issue #367 
Adding trailingDelta to new spot order request
=> Add trailingDelta to spot order service

v2/trade_service.go, v2/trade_service_test.go
Fixes [Missing quoteQty on Trade struct #382](https://github.com/adshao/go-binance/issues/382
) issue
=> Fixed missing quoteQty from recent and historical trades.

v2/client.go, v2/liquidity_pool_service.go, v2/liquidity_pool_service_test.go
-NewGetUserSwapRecordsService
-NewClaimRewardService
-NewRemoveLiquidityService
-NewQueryClaimedRewardHistoryService
=> Integrate more liquidity pool apis

v2/futures/client.go, v2/futures/mark_price_kline_service.go, v2/futures/mark_price_kline_service_test.go
Hi @adshao,
I have implemented MarkPriceKlinesService according to:
https://binance-docs.github.io/apidocs/futures/en/#mark-price-kline-candlestick-data
Thanks!
=> implement mark price klines

v2/futures/client.go, v2/futures/index_price_kline_service.go, v2/futures/index_price_kline_service_test.go
Hi @adshao !
Here is index price klines according to: 
https://binance-docs.github.io/apidocs/futures/en/#index-price-kline-candlestick-data
Thanks!
=> implement index price klines service

v2/ticker_service.go, v2/ticker_service_test.go
Addresses issue #406 
Added `windowSize` request parameter for `ListSymbolTickerService`
=> Added windowSize for ListSymbolTickerService

v2/websocket_service.go, v2/websocket_service_test.go
Addresses issue #409 
- Added `binance.WsCombinedTradeServe(...)` as combined alternative for `binance.WsTradeServe(...)`
- Added test for `binance.WsCombinedTradeServe(...)`
=> Added WsCombinedTradeServe(...)

v2/client.go, v2/internal_universal_transfer_service.go, v2/internal_universal_transfer_service_test.go
* InternalUniversalTransferService
* InternalUniversalTransferHistoryService
=> add internal universal transfer service

v2/asset_detail_service.go, v2/asset_detail_service_test.go, v2/client.go
=> feat implement GetUserAssetService

v2/futures/client.go, v2/futures/order_service.go, v2/futures/order_service_test.go
https://binance-docs.github.io/apidocs/futures/en/#query-current-open-order-user_data
=> feat implement GetOpenOrderService

v2/deposit_service.go
support user query deposit history by txId
=> feat  new parameter txId is added in ListDepositsService

v2/client.go, v2/subaccount_service.go, v2/subaccount_service_test.go
https://binance-docs.github.io/apidocs/spot/en/#get-sub-account-deposit-address-for-master-account
=> Add subaccount deposit address service.

v2/delivery/websocket.go, v2/futures/websocket.go, v2/websocket.go
=> disabled compression on websocket dialing

v2/websocket_service.go
add: 
- TrailingDelta           int64           `json:"d"`
- TrailingTime            int64           `json:"D"`
- StrategyId              int64           `json:"j"`
- StrategyType            int64           `json:"J"`
- WorkingTime             int64           `json:"W"`
- SelfTradePreventionMode string          `json:"V"`
=> update WsOrderUpdate struct (#441)

v2/ticker_service.go, v2/websocket_service_test.go
=> Fix go fmt & go vet

v2/margin_service.go, v2/margin_service_test.go
Ref: https://binance-docs.github.io/apidocs/spot/cn/#user_data-38
=> Add `enabled` field for the isolated margin account

v2/exchange_info_service.go, v2/exchange_info_service_test.go, v2/request.go
add new param `permissions` on get exchange info service.
=> add set permissions param on get exchange info service

v2/client.go, v2/margin_service.go, v2/margin_service_test.go
Ref: https://binance-docs.github.io/apidocs/spot/cn/#user_data-37
=> feat: implement IsolatedMarginTransferService

v2/client.go, v2/dust_log_service.go, v2/dust_log_service_test.go
Ref: https://binance-docs.github.io/apidocs/spot/en/#get-assets-that-can-be-converted-into-bnb-user_data
=> feat: Implement ListDustService

v2/client.go, v2/subaccount_service.go, v2/subaccount_service_test.go
1.  ManagedSubAccountDepositService
2. ManagedSubAccountWithdrawalService
3. ManagedSubAccountAssetsService
=> feat implement  managed sub account service

v2/futures/websocket_service.go, v2/futures/websocket_service_test.go
=> futures websocket support combined mark price streams

v2/futures/request.go, v2/futures/request_test.go
such as placeOrder use priceMatch or goodTillDate
=> added WithExtraForm help Add additional parameters to the form

v2/futures/order_service.go, v2/futures/order_service_test.go
Currently API errors are completly lost when creating multiple orders in a batch. I attempted to fix it by including errors in the response in a separate field so it's backwards-compatible.
=> Include API errors in CreateBatchOrdersResponse

v2/client.go, v2/websocket_service.go
able to change api endpoint
issue : #539
=> feat: support binance non global

README.md, v2/options/account_service.go, v2/options/account_service_test.go, v2/options/client.go, v2/options/client_test.go, v2/options/exercise_history_service.go, v2/options/exercise_history_service_test.go, v2/options/index_service.go, v2/options/index_service_test.go, v2/options/kline_service.go, v2/options/mark_service.go, v2/options/mark_service_test.go, v2/options/open_interest_service.go, v2/options/open_interest_service_test.go, v2/options/order_service.go, v2/options/order_service_test.go, v2/options/server_service.go, v2/options/server_service_test.go, v2/options/ticker_service.go, v2/options/ticker_service_test.go, v2/options/trade_service_test.go, v2/options/trades_service.go, v2/options/user_stream_service.go, v2/options/user_stream_service_test.go, v2/options/websocket.go, v2/options/websocket_service.go, v2/options/websocket_service_test.go
The complete implementation of the options module.
1. Implement unimplemented rest interfaces
2. Add implementation of websocket, all interfaces have been implemented
3. Fix some bugs
1. Fix the interface for batch order placement and cancellation. The original interface implementation was completely copied from the Futures module, but compared to the Binance official documentation, it was found that the parameter names were completely incorrect and could not be used in real transactions
2. In the account and transaction interface section, unify the return structure of interfaces related to orders and use the Order structure uniformly.
1. Why do we need to do this? Because the previous implementation appears to have been implemented and passed unit testing. But there are still many errors …
=> complete options module

.github/workflows/check.yml, README.md, typos.toml, v2/client.go, v2/delivery/account_service.go, v2/delivery/account_service_test.go, v2/delivery/client.go, v2/dust_log_service.go, v2/futures/client.go, v2/futures/websocket_service.go, v2/futures/websocket_service_test.go, v2/liquidity_pool_service.go, v2/options/client.go, v2/options/order_service.go, v2/websocket_service.go
1. fix current existly typos and add a typos check to avoid this in workflows of github.
=> fix current existly typos 

v2/client.go, v2/subaccount_service.go, v2/subaccount_service_test.go, v2/tradingDayTicker.go, v2/tradingDayTicker_test.go, v2/uiKlines_service.go, v2/uiKlines_service_test.go
1. Complete the existing interface for parent and child accounts.
2. Complete the interface for spot market trends;
=> complete sub-master interface(subaccount_service.go); complete spot market interface

v2/futures/client.go, v2/futures/fee_burn_service.go, v2/futures/fee_burn_service_test.go
add service Toggle-BNB-Burn-On-Futures-Trade
=> add fee burn service

v2/client.go, v2/simple_earn_service.go, v2/simple_earn_service_test.go
document at https://developers.binance.com/docs/simple_earn
=> add simple earn apis

.gitignore, v2/client.go, v2/delivery/client.go, v2/delivery/websocket_service.go, v2/futures/client.go, v2/futures/order_place_service_ws.go, v2/futures/order_service.go, v2/futures/websocket_service.go, v2/order_service.go
Hello, 
Added exported urls and self trade prevention mode param. 
Thanks
=> feat: export urls and added self trade prev mode into spot/futures client

v2/common/websocket/client.go, v2/futures/order_cancel_service_ws.go, v2/futures/order_place_service_ws.go, v2/order_service_ws_create.go
Hi, 
Small improvement for better testing on application side. 
And bugfix.
Thanks
=> feat: added getter for parameters of request (for testing needs)

v2/delivery/websocket.go, v2/futures/websocket.go, v2/options/websocket.go, v2/websocket.go
1. enable websocket compression, close #613
=> enable websocket compression

v2/client.go
1. fix #639 , This is the fundamental approach to fix this issue. Fix issue [Signature error when request parameter content includes @]
1. Currently, only the binance module has been repaired, and other modules have not been involved yet. Do not modify them for now.
=> fix signature error while the content includes @

v2/delivery/client.go, v2/delivery/funding_rate_service.go, v2/delivery/funding_rate_service_test.go
Add Funding Rate History for dapi
=> Add Get Funding Rate History for dapi

v2/client.go, v2/margin_service.go, v2/margin_service_test.go
=> Add MarginBorrowRepayService

v2/client.go, v2/margin_service.go, v2/margin_service_test.go
=> Add ListMarginBorrowRepayService

v2/margin_service.go, v2/margin_service_test.go
Added response fields for `GET /sapi/v1/margin/account` https://developers.binance.com/docs/margin_trading/account/Query-Cross-Margin-Account-Details
=> Added response fields for `GET /sapi/v1/margin/account`

v2/margin_service.go, v2/margin_service_test.go
As the documentation says, isIsolated and symbol are the two required fields.
https://developers.binance.com/docs/margin_trading/borrow-and-repay/Margin-Account-Borrow-Repay
=> fix MarginBorrowRepayService

v2/futures/client.go
- relates to https://github.com/ccxt/go-binance/issues/681
=> feat(futures): add gte_gtc tif

v2/common/websocket/client.go
Hello, 
Some improvements for better CPU usage when stop application and wait.
=> feat: remove spin lock while wait in ws client

v2/internal_universal_transfer_service.go, v2/internal_universal_transfer_service_test.go, v2/subaccount_service.go, v2/subaccount_service_test.go, v2/withdraw_service.go, v2/withdraw_service_test.go
- `InternalUniversalTransferService` https://developers.binance.com/docs/sub_account/asset-management/Universal-Transfer
- `ManagedSubAccountWithdrawalService` https://developers.binance.com/docs/sub_account/managed-sub-account/Withdrawl-Assets-From-The-Managed-Sub-account
- `CreateWithdrawService` https://developers.binance.com/docs/wallet/capital/withdraw
- `ListWithdrawsService` https://developers.binance.com/docs/wallet/capital/withdraw-history
- `ManagedSubAccountDepositService` https://developers.binance.com/docs/sub_account/managed-sub-account
=> feat: update internal_universal_Transfer/subaccount and withdraw

v2/futures/client.go
- fixes to https://github.com/ccxt/go-binance/issues/683
=> feat(futures): add GTD time in force

v2/account_commission_rate.go
- relates to https://github.com/ccxt/go-binance/issues/663
=> feat(client): add query account commission rate

v2/futures/api_trading_status_service.go, v2/futures/api_trading_status_service_test.go, v2/futures/client.go
ref: [Futures Trading Quantitative Rules Indicators](https://developers.binance.com/docs/derivatives/usds-margined-futures/account/rest-api/Futures-Trading-Quantitative-Rules-Indicators)
=> implement /fapi/v1/apiTradingStatus

v2/portfolio/client.go, v2/portfolio/user_stream_service.go, v2/portfolio/user_stream_service_integration_test.go, v2/portfolio/user_stream_service_test.go, v2/portfolio/websocket.go, v2/portfolio/websocket_service.go, v2/portfolio/websocket_service_integration_test.go, v2/portfolio/websocket_service_test.go
- **first commit**
- **fix orderId**
- **update readme**
- **fix tests**
- **fix**
- **fist commit**
=> feat: add support for portfolio websocket user stream

examples/main.go, examples/watcher.go, v2/websocket_service.go
=> Update testnet urls ws

v2/futures/order_service.go
=> chore: fix some typos in comment

v2/portfolio_pro/client.go, v2/portfolio_pro/client_test.go, v2/portfolio_pro/mint_bfusd_service.go, v2/portfolio_pro/mint_bfusd_service_test.go, v2/portfolio_pro/redeem_bfusd_service.go, v2/portfolio_pro/redeem_bfusd_service_test.go, v2/portfolio_pro/request.go
Support:
- Mint BFUSD: https://developers.binance.com/docs/derivatives/portfolio-margin-pro/account/Mint-BFUSD-Portfolio-Margin
- Redeem BFUSD: https://developers.binance.com/docs/derivatives/portfolio-margin-pro/account/Redeem-BFUSD-Portfolio-Margin
=> Feature: Add portfolio_pro mint/redeem BFUSD
